/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class AMPLI_CHANNEL {
  public final static AMPLI_CHANNEL AMP_NO_CHANNEL = new AMPLI_CHANNEL("AMP_NO_CHANNEL");
  public final static AMPLI_CHANNEL AMP_FRONT_CHANNEL = new AMPLI_CHANNEL("AMP_FRONT_CHANNEL");
  public final static AMPLI_CHANNEL AMP_REAR_CHANNEL = new AMPLI_CHANNEL("AMP_REAR_CHANNEL");
  public final static AMPLI_CHANNEL AMP_END_CHANNEL = new AMPLI_CHANNEL("AMP_END_CHANNEL");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static AMPLI_CHANNEL swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + AMPLI_CHANNEL.class + " with value " + swigValue);
  }

  private AMPLI_CHANNEL(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private AMPLI_CHANNEL(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private AMPLI_CHANNEL(String swigName, AMPLI_CHANNEL swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static AMPLI_CHANNEL[] swigValues = { AMP_NO_CHANNEL, AMP_FRONT_CHANNEL, AMP_REAR_CHANNEL, AMP_END_CHANNEL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

