/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class AMPLI_GAINS {
  public final static AMPLI_GAINS NO_GAIN = new AMPLI_GAINS("NO_GAIN");
  public final static AMPLI_GAINS LOW_GAIN12 = new AMPLI_GAINS("LOW_GAIN12");
  public final static AMPLI_GAINS HIGH_GAIN26 = new AMPLI_GAINS("HIGH_GAIN26");
  public final static AMPLI_GAINS END_GAIN = new AMPLI_GAINS("END_GAIN");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static AMPLI_GAINS swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + AMPLI_GAINS.class + " with value " + swigValue);
  }

  private AMPLI_GAINS(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private AMPLI_GAINS(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private AMPLI_GAINS(String swigName, AMPLI_GAINS swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static AMPLI_GAINS[] swigValues = { NO_GAIN, LOW_GAIN12, HIGH_GAIN26, END_GAIN };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

