/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class TouchMore {
  public static STATUS initDirana() {
    return STATUS.swigToEnum(TouchMoreJNI.initDirana());
  }

  public static STATUS setSource(DR_AUDIO_SOURCES_TYPES p_source) {
    return STATUS.swigToEnum(TouchMoreJNI.setSource(p_source.swigValue()));
  }

  public static STATUS getSource(SWIGTYPE_p_DR_AUDIO_SOURCES_TYPES p_source) {
    return STATUS.swigToEnum(TouchMoreJNI.getSource(SWIGTYPE_p_DR_AUDIO_SOURCES_TYPES.getCPtr(p_source)));
  }

  public static STATUS setVolume(int p_volume) {
    return STATUS.swigToEnum(TouchMoreJNI.setVolume(p_volume));
  }

  public static STATUS getVolume(SWIGTYPE_p_int p_volume) {
    return STATUS.swigToEnum(TouchMoreJNI.getVolume(SWIGTYPE_p_int.getCPtr(p_volume)));
  }

  public static STATUS setChannelGain(AMPLI_CHANNEL p_channel, AMPLI_GAINS p_gain) {
    return STATUS.swigToEnum(TouchMoreJNI.setChannelGain(p_channel.swigValue(), p_gain.swigValue()));
  }

  public static STATUS getChannelGain(AMPLI_CHANNEL p_channel, SWIGTYPE_p_AMPLI_GAINS p_gain) {
    return STATUS.swigToEnum(TouchMoreJNI.getChannelGain(p_channel.swigValue(), SWIGTYPE_p_AMPLI_GAINS.getCPtr(p_gain)));
  }

  public static STATUS playSin(int p_volume) {
    return STATUS.swigToEnum(TouchMoreJNI.playSin(p_volume));
  }

  public static STATUS doMute() {
    return STATUS.swigToEnum(TouchMoreJNI.doMute());
  }

  public static STATUS doDeMute() {
    return STATUS.swigToEnum(TouchMoreJNI.doDeMute());
  }

  public static STATUS change_band(TYPE_BAND p_new_band) {
    return STATUS.swigToEnum(TouchMoreJNI.change_band(p_new_band.swigValue()));
  }

  public static void get_band(TYPE_BAND TYPE_SUB_BAND, char p_subband) {
    TouchMoreJNI.get_band(TYPE_SUB_BAND.swigValue(), p_subband);
  }

  public static STATUS set_frequency(int p_frequency, TYPE_BAND p_band, TYPE_SUB_BAND p_subAM_band) {
    return STATUS.swigToEnum(TouchMoreJNI.set_frequency(p_frequency, p_band.swigValue(), p_subAM_band.swigValue()));
  }

  public static int get_frequency() {
    return TouchMoreJNI.get_frequency();
  }

  public static STATUS set_LeafDiceCfg(int p_freq, TYPE_BAND p_band, TYPE_SUB_BAND p_subAM_band) {
    return STATUS.swigToEnum(TouchMoreJNI.set_LeafDiceCfg(p_freq, p_band.swigValue(), p_subAM_band.swigValue()));
  }

  public static STATUS get_Freq_Band_fromTuner(SWIGTYPE_p_int p_freq, SWIGTYPE_p_TYPE_BAND p_band, SWIGTYPE_p_TYPE_SUB_BAND p_subband) {
    return STATUS.swigToEnum(TouchMoreJNI.get_Freq_Band_fromTuner(SWIGTYPE_p_int.getCPtr(p_freq), SWIGTYPE_p_TYPE_BAND.getCPtr(p_band), SWIGTYPE_p_TYPE_SUB_BAND.getCPtr(p_subband)));
  }

  public static STATUS setSourceAUX() {
    return STATUS.swigToEnum(TouchMoreJNI.setSourceAUX());
  }

  public static STATUS SetAuxOnPrimaryStereo() {
    return STATUS.swigToEnum(TouchMoreJNI.SetAuxOnPrimaryStereo());
  }

  public static STATUS SetTunerOnPrimaryStereo() {
    return STATUS.swigToEnum(TouchMoreJNI.SetTunerOnPrimaryStereo());
  }

  public static STATUS SetI2SOnPrimaryStereo() {
    return STATUS.swigToEnum(TouchMoreJNI.SetI2SOnPrimaryStereo());
  }

  public static STATUS SetCdcOnPrimaryStereo() {
    return STATUS.swigToEnum(TouchMoreJNI.SetCdcOnPrimaryStereo());
  }

  public static STATUS SetPhoneOnPrimaryStereo() {
    return STATUS.swigToEnum(TouchMoreJNI.SetPhoneOnPrimaryStereo());
  }

}
