/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class TYPE_BAND {
  public final static TYPE_BAND FM_BAND = new TYPE_BAND("FM_BAND");
  public final static TYPE_BAND AM_BAND = new TYPE_BAND("AM_BAND");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TYPE_BAND swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TYPE_BAND.class + " with value " + swigValue);
  }

  private TYPE_BAND(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TYPE_BAND(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TYPE_BAND(String swigName, TYPE_BAND swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TYPE_BAND[] swigValues = { FM_BAND, AM_BAND };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

