/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class TYPE_SUB_BAND {
  public final static TYPE_SUB_BAND AM_MW_BAND = new TYPE_SUB_BAND("AM_MW_BAND");
  public final static TYPE_SUB_BAND AM_KW_BAND = new TYPE_SUB_BAND("AM_KW_BAND");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TYPE_SUB_BAND swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TYPE_SUB_BAND.class + " with value " + swigValue);
  }

  private TYPE_SUB_BAND(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TYPE_SUB_BAND(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TYPE_SUB_BAND(String swigName, TYPE_SUB_BAND swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TYPE_SUB_BAND[] swigValues = { AM_MW_BAND, AM_KW_BAND };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

